---
- name: Create Spark worker systemd service
  template:
    src: spark-worker.service.j2
    dest: /etc/systemd/system/spark-worker.service
    mode: '0644'
  notify:
    - reload systemd
    - restart spark worker

- name: Enable and start Spark worker service
  systemd:
    name: spark-worker
    enabled: yes
    state: started
