---
# Kafka role default variables
kafka_version: "3.6.1"
scala_version: "2.13"
kafka_download_url: "https://archive.apache.org/dist/kafka/{{ kafka_version }}/kafka_{{ scala_version }}-{{ kafka_version }}.tgz"
kafka_home: "/opt/kafka"
kafka_port: 9092
kafka_log_dirs: "/var/lib/kafka-logs"
kafka_broker_id: 1
zookeeper_port: 2181
app_user: "spark"
app_group: "spark"
